# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: '"I:\Srikanth\Azure_Tosca\Client\ToscaCIClient.exe" -m local -c "I:\Srikanth\Azure_Tosca\configCI.xml" -t junit -r "C:\Tosca_Projects\result.xml"'
  displayName: 'Execute TOSCA Scripts'
- task: PublishTestResults@2
  displayName: 'Publish Results'
  inputs:
    failTaskOnFailedTests: true
    testRunTitle: 'Publish TOSCA Results'
